version: "2"
run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true

issues:
  exclude-use-default: false
